spring.application.name=module1introduction
#notification.type=emailNotif
spring.datasource.url=jdbc:mysql://localhost:3306/module1IntroDB?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=AshuGolu
spring.datasource.password=Ashu@Golu1
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
spring.jpa.hibernate.ddl-auto=update
#debug=true


