spring.application.name=module1introduction
#notification.type=emailNotif
spring.datasource.url=jdbc:h2:file:C:/Users/Dhriti/Desktop/codingShuttleDB/db
spring.datasource.username=ashishDB
spring.datasource.password=ashish123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.hibernate.ddl-auto=update
debug=true


