spring.application.name=SpringSecurity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/SpringSecurity?allowPublicKeyRetrieval=true&useSSL=false
# useSSL=true in production
spring.datasource.username=AshuGolu
spring.datasource.password=Ashu@Golu1

# port where our current application is running.
server.port = 9000


# Security config
# Here we can set the username and password for login in spring application. But this method of login form is not used in production.
#spring.security.user.name=Ashish
#spring.security.user.password=pass

jwt.secretKey=3451rhjdhfiwrj3h4r34rh4uhr9973nyugry4